apiVersion: apps/v1
kind: Deployment
metadata:
  name: railwaydeployment
  labels:
    app: railway

spec:
  replicas: 3
  selector:
    matchLabels:
      app: railway

  template:
    metadata:
      labels:
        app: railway

    spec:
      containers:
        - name: railwaycont
          image: jsaikumar9999/railimg:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: railwayservice

spec:
  type: LoadBalancer
  selector:
    app: railway
  ports:
    - port: 80
      targetPort: 80
